// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaN5PDVXX9ovYBguNl6lY64wPAkKC_qsY',
    appId: '1:1046711133934:web:5e95d71622a57861a375ff',
    messagingSenderId: '1046711133934',
    projectId: 'wordstory-fe3a3',
    authDomain: 'wordstory-fe3a3.firebaseapp.com',
    storageBucket: 'wordstory-fe3a3.firebasestorage.app',
    measurementId: 'G-LMSF694B7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAebwQhX3UTs4uhHtfnfoTQmkNOQBT1WmE',
    appId: '1:1046711133934:android:f53a6ffd8f135719a375ff',
    messagingSenderId: '1046711133934',
    projectId: 'wordstory-fe3a3',
    storageBucket: 'wordstory-fe3a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy9chgaAbJle2mz1xp1vnZOyR5s2hahzI',
    appId: '1:1046711133934:ios:a8aad85b1bfec408a375ff',
    messagingSenderId: '1046711133934',
    projectId: 'wordstory-fe3a3',
    storageBucket: 'wordstory-fe3a3.firebasestorage.app',
    iosBundleId: 'com.itnovax.wordstory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy9chgaAbJle2mz1xp1vnZOyR5s2hahzI',
    appId: '1:1046711133934:ios:a8aad85b1bfec408a375ff',
    messagingSenderId: '1046711133934',
    projectId: 'wordstory-fe3a3',
    storageBucket: 'wordstory-fe3a3.firebasestorage.app',
    iosBundleId: 'com.itnovax.wordstory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaN5PDVXX9ovYBguNl6lY64wPAkKC_qsY',
    appId: '1:1046711133934:web:6eb87180b90f3fcda375ff',
    messagingSenderId: '1046711133934',
    projectId: 'wordstory-fe3a3',
    authDomain: 'wordstory-fe3a3.firebaseapp.com',
    storageBucket: 'wordstory-fe3a3.firebasestorage.app',
    measurementId: 'G-VGGC23D3YC',
  );
}
